services:

  mysqldb:
    image: "mysql:8.0"
    ports:
      - 3306:3306
    volumes: 
      - crazy-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=project_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot:
    depends_on:
      - mysqldb
    build: ./back/coursDevOps
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/springboot?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck: 
      test: "curl http://localhost:8080/" 
      interval: 5s  
      timeout: 5s 
      retries: 5 
      start_period: 5s

  angular:
    depends_on:
      - springboot
    build: ./front/coursDevOps
    ports:
      - 80:4200

volumes:
  crazy-mysql-data