services:

  mysqldb:
    image: "mysql:8.0"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=project_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  springboot:
    depends_on:
      - mysqldb
    build: ./back/coursDevOps
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/springboot?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  angular:
    depends_on:
      - springboot
    build: ./front/coursDevOps
    ports:
      - 4200:80